### ISSUE TITLE
Not selecting camera image

### ISSUE THREAD

**Issue by Steffen1996** [mgks/Os-FileUp#10]
I can select camera from the intent chooser, i can make a photo, but as i click use, the webview does not respond anymore and the image is unselected. Device is SGS4.
Fiddle with this problem a couple days now, did not find a solution yet, hoped you solved it but nope.

**Comment by Steffen1996** [comment]
Nope, fixed it by myself. Problem was the launchMode - the activity got recreated after choosing cam image. Solution was adding the flag `android:launchMode="singleInstance"` to  the activity in manifest.

**Comment by mgks** [comment]
that's really good.
