### ISSUE TITLE
not chowing images

### ISSUE THREAD

**Issue by Allen013** [mgks/Os-FileUp#11]
It shows only documents option in the list, and it doesn't show gallery or images in the list after clicking upload from the website.

**Comment by mgks** [comment]
I hope you've resolved it by now.
Here's what may help you, look for `ASWV_F_TYPE` variable in _SmartWebView.java_ file.
Change the file type according to your need:
Use `"image/*"` for image instead of `"*/*"` (default).

Sorry for being late.
