### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [mgks/Os-FileUp#12]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by mgks** [comment]
sure. it would be nice.

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ?
![promo](https://user-images.githubusercontent.com/33461607/42449266-2dabd264-83aa-11e8-9538-de47f81d5f48.png)

**Comment by mgks** [comment]
looks beautiful. you should push the icon yourself, every contribution must count.

**Comment by mansya** [comment]
I have upload all file to this link
https://drive.google.com/open?id=1ybWvZEG642uE0CtMBidvdagxtTlX4QJY

And I have sent you pull request. please check

**Comment by mgks** [comment]
done. again, thank you.
