### ISSUE TITLE
File browser shows even if permission denied

### ISSUE THREAD

**Issue by elitree** [mgks/Os-FileUp#16]
Thanks for the great reference code!

I noticed an issue which I wanted to point out... if I run the project and deny the permissions dialogs which show at startup, and then click the Choose File button in the webpage, the file browser shows up, even though I haven't given permission for accessing external files. I would expect the file browser to be suppressed until permission is given for accessing external files. 

I'm using multiple_files = false, and running the project on a Pixel 2 simulator running Android 8.1.

Thanks again!

**Comment by mgks** [comment]
Hi,
Thanks and sorry for the late response.

I've fixed the bug by adding condition to check permissions before file explorer clause. You can test the repo and let me know.

And happy new year!

**Comment by elitree** [comment]
This change works great both in the sample and my own app where I'm implementing it. Thanks for the quick fix!
