### ISSUE TITLE
Page reload on screen rotate

### ISSUE THREAD

**Issue by thusfar7** [mgks/Os-FileUp#2]
Everytime I rotate my screen the webview reloads. How to prevent thaat?

Thanks

**Comment by mgks** [comment]
I've tested it on different devices and works fine till API 16 and this app is made to demonstrate File Upload but thanks for centering my attention to this issue.

You can add these classes to MainActivity:

```
if (savedInstanceState == null){
  web.loadUrl(webURL);
}
```
```
@Override
protected void onSaveInstanceState(Bundle outState){
super.onSaveInstanceState(outState);
web.saveState(outState);
}

@Override
protected void onRestoreInstanceState(Bundle savedInstanceState){
super.onRestoreInstanceState(savedInstanceState);
web.restoreState(savedInstanceState);
}
```
**OR**
Add these lines into AndroidManifest's activity nod:
```
<activity 
android:name=".MainActivity"
android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize">
```

Hope this helps! Try contributing to the project, any better change will be appreciated :)

**Comment by mgks** [comment]
I think the issue is resolved, but I'd still like to get your feedback. So re-open the issue if needed!
