### ISSUE TITLE
Camera Only without File Chooser

### ISSUE THREAD

**Issue by hugeps** [mgks/Os-FileUp#22]
Is this possible to do a camera only so that chooser is not even shown, i.e. straight to camera?
Definitely more than one coffee for solving that problem :)

**Comment by mgks** [comment]
I'll always appreciate a cup of coffee no matter the quantity. But I've already got this one solved.

Just comment out these lines from `MainActivity.java`
```
contentSelectionIntent.addCategory(Intent.CATEGORY_OPENABLE);
contentSelectionIntent.setType(file_type);
if (multiple_files) {
    contentSelectionIntent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
}
```

A coffee would still be appreciated :)
