### ISSUE TITLE
Why Camera option not implemented for Android 3.0, 4.1 devices?

### ISSUE THREAD

**Issue by praveenb** [mgks/Os-FileUp#3]
Hi Khan,

I just have a question. Why camera option not implemented for Android 3.0, 4.1 devices.

Its really helped me, Thank you so much for it.

Please reply.
Thanks again.

**Comment by mgks** [comment]
sorry for being so late, I was into something else.
Actually, I made this project as demo and was in little hurry to catch up with my next project, sorry for that.
But, I'm also working on a better webView in my free time now, I'm sure, you'll love it. It will have all the implementations needed and thanks for the mail.

**Comment by mgks** [comment]
[Android SmartWebView](https://github.com/mgks/Android-SmartWebView) can help people who are looking for the solution of this particular problem.

`Bonus: 4.1 officially doesn't supports this option and is buggy. Sorry for that, Google to blame.`
