### ISSUE TITLE
Still not work on Android 10, got Activity.RESULT_CANCELED imediately.

### ISSUE THREAD

**Issue by qsjh898** [mgks/Os-FileUp#31]
I tried running the latest demo on my **HUAWEI MATE30(Android 10)** and got `Activity.RESULT_CANCELED` imediately after I select Camera on dialog. But it worked well on **Android 7**. Sorry for my poor English.

**Comment by qsjh898** [comment]
Seems bug of HUAWEI. It works fine on other Android 10 phones.

**Comment by mgks** [comment]
It's happening across devices man! I just tried so many ways to fix it, it's completely on what device you use, current codes work on majority of Android 10 devices but some have their own issues. Really hard to make it compatible for all.

**Comment by amanzan** [comment]
any updates on this? anything I could do to help? Not sure why it always gives Activity.RESULT_CANCELLED...and only on Huawei as @qsjh898 said. I have a Redmi device and works just fine

**Comment by qsjh898** [comment]
@amanzan Avoid setting `MediaStore.EXTRA_OUTPUT` on Huawei can solve this problem to some extent.
