### ISSUE TITLE
Upload document and image

### ISSUE THREAD

**Issue by WaKeMaTTa** [mgks/Os-FileUp#4]
Thanks for the code.

I have one question. If i want to upload some document (lets say `.docx`) what i need to change in the code?

**Comment by mgks** [comment]
There is a little code on line 100, like this:
`i.setType("image/*");`

This same phrase is used few more times in the code overall. Just change the file type "image" to get your desired file type. Like in your case, you can use:
`i.setType("application/*");` to select pdf, docs and more application files.

For specific MS Word:
`i.setType("application/msword");`

But, if you want to restrict it for multiple file types, use:
`i.setType("image/*|application/*|audio/*");`

Or, for all file types, just change it all to an asterix:
`i.setType("*");`

I'll be soon publishing a new open source Smart webView with more simple customizations, hope it helps. And thanks for the personal mail.

**Comment by WaKeMaTTa** [comment]
Thanks that is what i need it =D 

Thanks a lot!

**Comment by WaKeMaTTa** [comment]
@mgks 1 more question

I did set `i.setTupe("*");`, but I need to know the extension of the file uploaded for it for this line: https://github.com/mgks/Os-FileUp/blob/master/app/src/main/java/com/inf/os/fileup/MainActivity.java#L174

Can you tell me how?

Thanks in advance.
