### ISSUE TITLE
Null pointer exception Feedback

### ISSUE THREAD

**Issue by hasanmumin** [mgks/Os-FileUp#8]
https://github.com/mgks/Os-FileUp/blob/master/app/src/main/java/com/inf/os/fileup/MainActivity.java#L51

Android 7.1.1 intent is null, so intent.getData() throw null pointer exception,
it should be 
`if (intent == null || intent.getData() == null) `

Thanks.

**Comment by mgks** [comment]
Thanks man!
I didn't tested the program after last commit update by other user. Updated now.
