### ISSUE TITLE
acceptType Feedback

### ISSUE THREAD

**Issue by hasanmumin** [mgks/Os-FileUp#9]
you default set  acceptType = > " \*/\* " in openFileChooser methods. 
it should be setting by acceptType parameter.
//For Android 5.0+ => it is inside at FileChooserParams. 

Thanks for amazing example.

**Comment by mgks** [comment]
Oh man, I'm extremely sorry for checking this in 2018 (this late). Thanks for your help, I'll definitely see what improvements can be made and will surely update ASAP. Till then, I'll keep this issue open to keep myself in check.

And you're welcome! 👍
